import * as Addresses from './addresses';
import * as Departments from './departments';
import * as Devices from './devices';
import * as Enums from './enums';
import * as Factories from './factories';
import * as Indicators from './indicators';
import * as MailTemplates from './mail-templates';
import * as Microsoft from './microsoft';
import * as Profilings from './profilings';
import * as Reports from './reports';
import * as Roles from './roles';
import * as Sepomex from './sepomex';
import * as UserTypes from './user-types';
import * as Users from './users';
import * as Volo from './volo';
import * as Warehouses from './warehouses';
export * from './models';
export * from './multifarious.service';
export { Addresses, Departments, Devices, Enums, Factories, Indicators, MailTemplates, Microsoft, Profilings, Reports, Roles, Sepomex, UserTypes, Users, Volo, Warehouses };
